# Site Settings
title: "陈雯欣学术主页"
email: "wenxinchen_shu@foxmail.com"
description: "陈雯欣的个人学术网站 - 专注于家庭社会学、妇女/性别研究、社会心理学"
url: "https://[您的GitHub用户名].github.io"

# Site Author
author:
  name: "陈雯欣"
  avatar: "/images/profile.jpg"  # 上传您的照片
  bio: "上海大学经济学院金融专业硕士研究生"
  location: "上海, 中国"
  employer: "上海大学"
  email: "wenxinchen_shu@foxmail.com"
  phone: "15394212501"
  researchgate: # 如果有的话
  googlescholar: # 如果有的话
  orcid: # 如果有的话
